import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { Toaster } from '@/components/ui/toaster'
import { StoreProvider } from '@/store'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = cookies()
  const userInfo: { [key: string]: any } = {}
  cookieStore.getAll().map((cookie) => {
    userInfo[cookie.name] = cookie.value
  })

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider initialValue={{ userInfo }}>
          <>
            <Navbar />
            {children}
            <Footer />
            <Toaster />
          </>
        </StoreProvider>
      </body>
    </html>
  )
}
